"""add featured_file_id to user_locations and scripted_locations

Revision ID: 24091545eac9
Revises: 30cc1d54bcee
Create Date: 2026-02-16 15:24:25.705336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24091545eac9'
down_revision: Union[str, None] = '30cc1d54bcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripted_locations', sa.Column('featured_file_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_scripted_locations_featured_file_id'), 'scripted_locations', ['featured_file_id'], unique=False)
    op.create_foreign_key(op.f('fk_scripted_locations_featured_file_id_files'), 'scripted_locations', 'files', ['featured_file_id'], ['id'], ondelete='SET NULL')
    op.add_column('user_locations', sa.Column('featured_file_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_user_locations_featured_file_id'), 'user_locations', ['featured_file_id'], unique=False)
    op.create_foreign_key(op.f('fk_user_locations_featured_file_id_files'), 'user_locations', 'files', ['featured_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_locations_featured_file_id_files'), 'user_locations', type_='foreignkey')
    op.drop_index(op.f('ix_user_locations_featured_file_id'), table_name='user_locations')
    op.drop_column('user_locations', 'featured_file_id')
    op.drop_constraint(op.f('fk_scripted_locations_featured_file_id_files'), 'scripted_locations', type_='foreignkey')
    op.drop_index(op.f('ix_scripted_locations_featured_file_id'), table_name='scripted_locations')
    op.drop_column('scripted_locations', 'featured_file_id')
    # ### end Alembic commands ###
