"""Add SmugMug tables

Revision ID: 4c4cb6c093dc
Revises: 57cf0c3b7f79
Create Date: 2026-02-17 03:30:18.939561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4cb6c093dc'
down_revision: Union[str, None] = '57cf0c3b7f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smugmug_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_smugmug_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smugmug_accounts'))
    )
    op.create_index(op.f('ix_smugmug_accounts_user_id'), 'smugmug_accounts', ['user_id'], unique=False)
    op.create_table('smugmug_folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('smugmug_uri', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('url_path', sa.String(length=1000), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['smugmug_accounts.id'], name=op.f('fk_smugmug_folders_account_id_smugmug_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['smugmug_folders.id'], name=op.f('fk_smugmug_folders_parent_id_smugmug_folders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smugmug_folders')),
    sa.UniqueConstraint('account_id', 'smugmug_uri', name='uq_smugmug_folder_uri')
    )
    op.create_index(op.f('ix_smugmug_folders_account_id'), 'smugmug_folders', ['account_id'], unique=False)
    op.create_table('smugmug_galleries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('smugmug_uri', sa.String(length=500), nullable=False),
    sa.Column('smugmug_album_key', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('url_path', sa.String(length=1000), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['smugmug_accounts.id'], name=op.f('fk_smugmug_galleries_account_id_smugmug_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['smugmug_folders.id'], name=op.f('fk_smugmug_galleries_folder_id_smugmug_folders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smugmug_galleries')),
    sa.UniqueConstraint('account_id', 'smugmug_uri', name='uq_smugmug_gallery_uri')
    )
    op.create_index(op.f('ix_smugmug_galleries_account_id'), 'smugmug_galleries', ['account_id'], unique=False)
    op.create_table('smugmug_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('smugmug_uri', sa.String(length=500), nullable=False),
    sa.Column('smugmug_image_key', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('smugmug_url', sa.String(length=1000), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_smugmug_images_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gallery_id'], ['smugmug_galleries.id'], name=op.f('fk_smugmug_images_gallery_id_smugmug_galleries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smugmug_images')),
    sa.UniqueConstraint('gallery_id', 'smugmug_uri', name='uq_smugmug_image_uri')
    )
    op.create_index(op.f('ix_smugmug_images_gallery_id'), 'smugmug_images', ['gallery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smugmug_images_gallery_id'), table_name='smugmug_images')
    op.drop_table('smugmug_images')
    op.drop_index(op.f('ix_smugmug_galleries_account_id'), table_name='smugmug_galleries')
    op.drop_table('smugmug_galleries')
    op.drop_index(op.f('ix_smugmug_folders_account_id'), table_name='smugmug_folders')
    op.drop_table('smugmug_folders')
    op.drop_index(op.f('ix_smugmug_accounts_user_id'), table_name='smugmug_accounts')
    op.drop_table('smugmug_accounts')
    # ### end Alembic commands ###
