"""add scripted locations tables

Revision ID: 509d6147e1a1
Revises: addde799e3ed
Create Date: 2026-02-15 19:45:45.686230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509d6147e1a1'
down_revision: Union[str, None] = 'addde799e3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('episodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_episodes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes'))
    )
    op.create_index(op.f('ix_episodes_project_id'), 'episodes', ['project_id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk_folders_parent_id_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_folders_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders'))
    )
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_project_id'), 'folders', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_members'))
    )
    op.create_table('scoutings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('scouted_by_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scouted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_scoutings_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scouted_by_id'], ['users.id'], name=op.f('fk_scoutings_scouted_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoutings'))
    )
    op.create_index(op.f('ix_scoutings_location_id'), 'scoutings', ['location_id'], unique=False)
    op.create_index(op.f('ix_scoutings_scouted_by_id'), 'scoutings', ['scouted_by_id'], unique=False)
    op.create_table('scripted_locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_scripted_locations_episode_id_episodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_scripted_locations_folder_id_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scripted_locations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripted_locations'))
    )
    op.create_index(op.f('ix_scripted_locations_episode_id'), 'scripted_locations', ['episode_id'], unique=False)
    op.create_index(op.f('ix_scripted_locations_folder_id'), 'scripted_locations', ['folder_id'], unique=False)
    op.create_index(op.f('ix_scripted_locations_project_id'), 'scripted_locations', ['project_id'], unique=False)
    op.create_table('scripted_location_locations',
    sa.Column('scripted_location_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('added_by_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_scripted_location_locations_added_by_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_scripted_location_locations_location_id_locations')),
    sa.ForeignKeyConstraint(['scripted_location_id'], ['scripted_locations.id'], name=op.f('fk_scripted_location_locations_scripted_location_id_scripted_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scripted_location_id', 'location_id', name=op.f('pk_scripted_location_locations'))
    )
    op.add_column('files', sa.Column('scouting_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_files_scouting_id'), 'files', ['scouting_id'], unique=False)
    op.create_foreign_key(op.f('fk_files_scouting_id_scoutings'), 'files', 'scoutings', ['scouting_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_files_scouting_id_scoutings'), 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_scouting_id'), table_name='files')
    op.drop_column('files', 'scouting_id')
    op.drop_table('scripted_location_locations')
    op.drop_index(op.f('ix_scripted_locations_project_id'), table_name='scripted_locations')
    op.drop_index(op.f('ix_scripted_locations_folder_id'), table_name='scripted_locations')
    op.drop_index(op.f('ix_scripted_locations_episode_id'), table_name='scripted_locations')
    op.drop_table('scripted_locations')
    op.drop_index(op.f('ix_scoutings_scouted_by_id'), table_name='scoutings')
    op.drop_index(op.f('ix_scoutings_location_id'), table_name='scoutings')
    op.drop_table('scoutings')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_folders_project_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_episodes_project_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('projects')
    # ### end Alembic commands ###
