"""add user_folders and folder_id to user_locations

Revision ID: 57cf0c3b7f79
Revises: ae051b5854bb
Create Date: 2026-02-17 03:28:57.806501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cf0c3b7f79'
down_revision: Union[str, None] = 'ae051b5854bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_user_folders_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['user_folders.id'], name=op.f('fk_user_folders_parent_id_user_folders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_folders'))
    )
    op.create_index(op.f('ix_user_folders_owner_id'), 'user_folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_user_folders_parent_id'), 'user_folders', ['parent_id'], unique=False)
    op.add_column('user_locations', sa.Column('folder_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_user_locations_folder_id'), 'user_locations', ['folder_id'], unique=False)
    op.create_foreign_key(op.f('fk_user_locations_folder_id_user_folders'), 'user_locations', 'user_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_locations_folder_id_user_folders'), 'user_locations', type_='foreignkey')
    op.drop_index(op.f('ix_user_locations_folder_id'), table_name='user_locations')
    op.drop_column('user_locations', 'folder_id')
    op.drop_index(op.f('ix_user_folders_parent_id'), table_name='user_folders')
    op.drop_index(op.f('ix_user_folders_owner_id'), table_name='user_folders')
    op.drop_table('user_folders')
    # ### end Alembic commands ###
