"""Remove smugmug_nick from smugmug_accounts

Revision ID: 8ed504ac4775
Revises: b1be66557dcb
Create Date: 2026-02-18 03:11:24.310787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed504ac4775'
down_revision: Union[str, None] = 'b1be66557dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smugmug_accounts', 'smugmug_nick')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smugmug_accounts', sa.Column('smugmug_nick', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
