"""create all tables

Revision ID: addde799e3ed
Revises: 
Create Date: 2026-02-15 18:02:01.707918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addde799e3ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_locations_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index(op.f('ix_locations_owner_id'), 'locations', ['owner_id'], unique=False)
    op.create_table('production_members',
    sa.Column('production_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_production_members_production_id_productions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_production_members_user_id_users')),
    sa.PrimaryKeyConstraint('production_id', 'user_id', name=op.f('pk_production_members'))
    )
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_files_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index(op.f('ix_files_location_id'), 'files', ['location_id'], unique=False)
    op.create_table('location_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('shared_by_id', sa.Uuid(), nullable=False),
    sa.Column('shared_with_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_location_shares_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_id'], ['users.id'], name=op.f('fk_location_shares_shared_by_id_users')),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], name=op.f('fk_location_shares_shared_with_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_shares')),
    sa.UniqueConstraint('location_id', 'shared_with_id', name=op.f('uq_location_shares_location_id'))
    )
    op.create_index(op.f('ix_location_shares_location_id'), 'location_shares', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_shares_shared_with_id'), 'location_shares', ['shared_with_id'], unique=False)
    op.create_table('production_locations',
    sa.Column('production_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('added_by_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_production_locations_added_by_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_production_locations_location_id_locations')),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_production_locations_production_id_productions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('production_id', 'location_id', name=op.f('pk_production_locations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_locations')
    op.drop_index(op.f('ix_location_shares_shared_with_id'), table_name='location_shares')
    op.drop_index(op.f('ix_location_shares_location_id'), table_name='location_shares')
    op.drop_table('location_shares')
    op.drop_index(op.f('ix_files_location_id'), table_name='files')
    op.drop_table('files')
    op.drop_table('production_members')
    op.drop_index(op.f('ix_locations_owner_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('users')
    op.drop_table('productions')
    # ### end Alembic commands ###
