"""drop production tables

Revision ID: ae051b5854bb
Revises: a1b2c3d4e5f6
Create Date: 2026-02-17 00:27:47.698672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae051b5854bb'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_locations')
    op.drop_table('production_members')
    op.drop_table('productions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_members',
    sa.Column('production_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_production_members_production_id_productions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_production_members_user_id_users')),
    sa.PrimaryKeyConstraint('production_id', 'user_id', name=op.f('pk_production_members'))
    )
    op.create_table('production_locations',
    sa.Column('production_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_production_locations_added_by_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['user_locations.id'], name=op.f('fk_production_locations_location_id_user_locations')),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], name=op.f('fk_production_locations_production_id_productions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('production_id', 'location_id', name=op.f('pk_production_locations'))
    )
    op.create_table('productions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productions'))
    )
    # ### end Alembic commands ###
