"""Remove nickname from smugmug_accounts

Revision ID: b1be66557dcb
Revises: e2bc1cee1223
Create Date: 2026-02-18 02:35:34.915095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1be66557dcb'
down_revision: Union[str, None] = 'e2bc1cee1223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smugmug_accounts', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smugmug_accounts', sa.Column('nickname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
